server:
  port: 80
spring:
  application:
    name: spbbase-gateway
  cloud:
    gateway:
      #      discovery:
      #        locator:
      #          enabled: true
      #          lower-case-service-id: true
      routes:
        - id: web_route
          order: 100
          uri: http://localhost:8000
          predicates:
            - Path= /**
        - id: spbbase-authcenter-web
          uri: lb://spbbase-authcenter-web
          predicates:
            - Path=/spbbase-authcenter-web/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: trace
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"