spring:
  application:
    name: biz-finance
  #  liquibase:
  #    enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fm_data?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 888888
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1
server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
swagger:
  enabled: true